/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


typedef char nomeFile_t[20];
#ifdef __cplusplus
extern "C" bool_t xdr_nomeFile_t(XDR *, nomeFile_t);
#elif __STDC__
extern  bool_t xdr_nomeFile_t(XDR *, nomeFile_t);
#else /* Old Style C */
bool_t xdr_nomeFile_t();
#endif /* Old Style C */


typedef char nomeDir_t[20];
#ifdef __cplusplus
extern "C" bool_t xdr_nomeDir_t(XDR *, nomeDir_t);
#elif __STDC__
extern  bool_t xdr_nomeDir_t(XDR *, nomeDir_t);
#else /* Old Style C */
bool_t xdr_nomeDir_t();
#endif /* Old Style C */


struct Inputdir {
	nomeDir_t nomeDir;
	char carattere;
	int occorrenze;
};
typedef struct Inputdir Inputdir;
#ifdef __cplusplus
extern "C" bool_t xdr_Inputdir(XDR *, Inputdir*);
#elif __STDC__
extern  bool_t xdr_Inputdir(XDR *, Inputdir*);
#else /* Old Style C */
bool_t xdr_Inputdir();
#endif /* Old Style C */


struct OutputLista {
	nomeFile_t nomeFile[7];
	int numero_file_trovati;
};
typedef struct OutputLista OutputLista;
#ifdef __cplusplus
extern "C" bool_t xdr_OutputLista(XDR *, OutputLista*);
#elif __STDC__
extern  bool_t xdr_OutputLista(XDR *, OutputLista*);
#else /* Old Style C */
bool_t xdr_OutputLista();
#endif /* Old Style C */


#define GESTIONE_FILE_PROG ((rpc_uint)0x20000015)
#define GESTIONE_FILE_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ELIMINA_OCCORRENZE ((rpc_uint)1)
extern "C" int * elimina_occorrenze_1(char *, CLIENT *);
extern "C" int * elimina_occorrenze_1_svc(char *, struct svc_req *);
#define LISTA_FILE_CARATTERE ((rpc_uint)2)
extern "C" OutputLista * lista_file_carattere_1(Inputdir *, CLIENT *);
extern "C" OutputLista * lista_file_carattere_1_svc(Inputdir *, struct svc_req *);

#elif __STDC__
#define ELIMINA_OCCORRENZE ((rpc_uint)1)
extern  int * elimina_occorrenze_1(char *, CLIENT *);
extern  int * elimina_occorrenze_1_svc(char *, struct svc_req *);
#define LISTA_FILE_CARATTERE ((rpc_uint)2)
extern  OutputLista * lista_file_carattere_1(Inputdir *, CLIENT *);
extern  OutputLista * lista_file_carattere_1_svc(Inputdir *, struct svc_req *);

#else /* Old Style C */
#define ELIMINA_OCCORRENZE ((rpc_uint)1)
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
#define LISTA_FILE_CARATTERE ((rpc_uint)2)
extern  OutputLista * lista_file_carattere_1();
extern  OutputLista * lista_file_carattere_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
