/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_nomeFile_t(xdrs, objp)
	XDR *xdrs;
	nomeFile_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nomeDir_t(xdrs, objp)
	XDR *xdrs;
	nomeDir_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Inputdir(xdrs, objp)
	XDR *xdrs;
	Inputdir *objp;
{

	if (!xdr_nomeDir_t(xdrs, objp->nomeDir))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->carattere))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->occorrenze))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_OutputLista(xdrs, objp)
	XDR *xdrs;
	OutputLista *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->nomeFile, 7, sizeof(nomeFile_t), (xdrproc_t)xdr_nomeFile_t))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->numero_file_trovati))
		return (FALSE);
	return (TRUE);
}
