/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_nome_t (XDR *xdrs, nome_t objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAX_FILENAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_host_t (XDR *xdrs, host_t objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAX_NAMELEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_err_t (XDR *xdrs, err_t objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAX_ERRMSG,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Info (XDR *xdrs, Info *objp)
{
	register int32_t *buf;

	 if (!xdr_nome_t (xdrs, objp->nomefile))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Risposta (XDR *xdrs, Risposta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->files, MAX_FILES,
		sizeof (Info), (xdrproc_t) xdr_Info))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_files))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_err_t (xdrs, objp->errmsg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PuntoClient (XDR *xdrs, PuntoClient *objp)
{
	register int32_t *buf;

	 if (!xdr_host_t (xdrs, objp->host))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_nome_t (xdrs, objp->dirname))
		 return FALSE;
	return TRUE;
}
