/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_FILES 20
#define MAX_FILENAME 20
#define MAX_NAMELEN 20
#define MAX_ERRMSG 64

typedef char nome_t[MAX_FILENAME];

typedef char host_t[MAX_NAMELEN];

typedef char err_t[MAX_ERRMSG];

struct Info {
	nome_t nomefile;
	long size;
};
typedef struct Info Info;

struct Risposta {
	Info files[MAX_FILES];
	int num_files;
	int port;
	err_t errmsg;
};
typedef struct Risposta Risposta;

struct PuntoClient {
	host_t host;
	int port;
	nome_t dirname;
};
typedef struct PuntoClient PuntoClient;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETLISTA 1
extern  Risposta * getlista_1(char *, CLIENT *);
extern  Risposta * getlista_1_svc(char *, struct svc_req *);
#define GETLISTA_SA 2
extern  Risposta * getlista_sa_1(PuntoClient *, CLIENT *);
extern  Risposta * getlista_sa_1_svc(PuntoClient *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETLISTA 1
extern  Risposta * getlista_1();
extern  Risposta * getlista_1_svc();
#define GETLISTA_SA 2
extern  Risposta * getlista_sa_1();
extern  Risposta * getlista_sa_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome_t (XDR *, nome_t);
extern  bool_t xdr_host_t (XDR *, host_t);
extern  bool_t xdr_err_t (XDR *, err_t);
extern  bool_t xdr_Info (XDR *, Info*);
extern  bool_t xdr_Risposta (XDR *, Risposta*);
extern  bool_t xdr_PuntoClient (XDR *, PuntoClient*);

#else /* K&R C */
extern bool_t xdr_nome_t ();
extern bool_t xdr_host_t ();
extern bool_t xdr_err_t ();
extern bool_t xdr_Info ();
extern bool_t xdr_Risposta ();
extern bool_t xdr_PuntoClient ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XFACTOR_H_RPCGEN */
