/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "xfactor.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Risposta *
getlista_1(char *argp, CLIENT *clnt)
{
	static Risposta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETLISTA,
		(xdrproc_t) xdr_nome_t, (caddr_t) argp,
		(xdrproc_t) xdr_Risposta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Risposta *
getlista_sa_1(PuntoClient *argp, CLIENT *clnt)
{
	static Risposta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETLISTA_SA,
		(xdrproc_t) xdr_PuntoClient, (caddr_t) argp,
		(xdrproc_t) xdr_Risposta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
