/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


typedef char nome_t[20];
#ifdef __cplusplus
extern "C" bool_t xdr_nome_t(XDR *, nome_t);
#elif __STDC__
extern  bool_t xdr_nome_t(XDR *, nome_t);
#else /* Old Style C */
bool_t xdr_nome_t();
#endif /* Old Style C */


typedef char cognome_t[20];
#ifdef __cplusplus
extern "C" bool_t xdr_cognome_t(XDR *, cognome_t);
#elif __STDC__
extern  bool_t xdr_cognome_t(XDR *, cognome_t);
#else /* Old Style C */
bool_t xdr_cognome_t();
#endif /* Old Style C */


typedef char matricola_t[10];
#ifdef __cplusplus
extern "C" bool_t xdr_matricola_t(XDR *, matricola_t);
#elif __STDC__
extern  bool_t xdr_matricola_t(XDR *, matricola_t);
#else /* Old Style C */
bool_t xdr_matricola_t();
#endif /* Old Style C */


struct Studente {
	nome_t nome;
	cognome_t cognome;
	matricola_t matricola;
	int voto;
};
typedef struct Studente Studente;
#ifdef __cplusplus
extern "C" bool_t xdr_Studente(XDR *, Studente*);
#elif __STDC__
extern  bool_t xdr_Studente(XDR *, Studente*);
#else /* Old Style C */
bool_t xdr_Studente();
#endif /* Old Style C */


struct OutputLista {
	struct Studente studenti[5];
	int numero_studenti_trovati;
};
typedef struct OutputLista OutputLista;
#ifdef __cplusplus
extern "C" bool_t xdr_OutputLista(XDR *, OutputLista*);
#elif __STDC__
extern  bool_t xdr_OutputLista(XDR *, OutputLista*);
#else /* Old Style C */
bool_t xdr_OutputLista();
#endif /* Old Style C */


#define GESTIONE_STUDENTI_PROG ((rpc_uint)0x20000015)
#define GESTIONE_STUDENTI_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern "C" int * elimina_prenotazione_1(char *, CLIENT *);
extern "C" int * elimina_prenotazione_1_svc(char *, struct svc_req *);
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA ((rpc_uint)2)
extern "C" OutputLista * visualizza_voto_maggiore_soglia_1(int *, CLIENT *);
extern "C" OutputLista * visualizza_voto_maggiore_soglia_1_svc(int *, struct svc_req *);

#elif __STDC__
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern  int * elimina_prenotazione_1(char *, CLIENT *);
extern  int * elimina_prenotazione_1_svc(char *, struct svc_req *);
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA ((rpc_uint)2)
extern  OutputLista * visualizza_voto_maggiore_soglia_1(int *, CLIENT *);
extern  OutputLista * visualizza_voto_maggiore_soglia_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern  int * elimina_prenotazione_1();
extern  int * elimina_prenotazione_1_svc();
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA ((rpc_uint)2)
extern  OutputLista * visualizza_voto_maggiore_soglia_1();
extern  OutputLista * visualizza_voto_maggiore_soglia_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
