/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_nome_t(xdrs, objp)
	XDR *xdrs;
	nome_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cognome_t(xdrs, objp)
	XDR *xdrs;
	cognome_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_matricola_t(xdrs, objp)
	XDR *xdrs;
	matricola_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 10, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Studente(xdrs, objp)
	XDR *xdrs;
	Studente *objp;
{

	if (!xdr_nome_t(xdrs, objp->nome))
		return (FALSE);
	if (!xdr_cognome_t(xdrs, objp->cognome))
		return (FALSE);
	if (!xdr_matricola_t(xdrs, objp->matricola))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->voto))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_OutputLista(xdrs, objp)
	XDR *xdrs;
	OutputLista *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->studenti, 5, sizeof(Studente), (xdrproc_t)xdr_Studente))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->numero_studenti_trovati))
		return (FALSE);
	return (TRUE);
}
