/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_targa_t(xdrs, objp)
	XDR *xdrs;
	targa_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 8, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_patente_t(xdrs, objp)
	XDR *xdrs;
	patente_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 6, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_tipo_t(xdrs, objp)
	XDR *xdrs;
	tipo_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 10, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_img_t(xdrs, objp)
	XDR *xdrs;
	img_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 12, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Prenotazione(xdrs, objp)
	XDR *xdrs;
	Prenotazione *objp;
{

	if (!xdr_targa_t(xdrs, objp->targa))
		return (FALSE);
	if (!xdr_patente_t(xdrs, objp->patente))
		return (FALSE);
	if (!xdr_tipo_t(xdrs, objp->tipo))
		return (FALSE);
	if (!xdr_img_t(xdrs, objp->img))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Input(xdrs, objp)
	XDR *xdrs;
	Input *objp;
{

	if (!xdr_targa_t(xdrs, objp->targa))
		return (FALSE);
	if (!xdr_patente_t(xdrs, objp->patente))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_OutputLista(xdrs, objp)
	XDR *xdrs;
	OutputLista *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->prenotazioni, 6, sizeof(Prenotazione), (xdrproc_t)xdr_Prenotazione))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->numero_prenotazioni_trovati))
		return (FALSE);
	return (TRUE);
}
