/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


typedef char targa_t[8];
#ifdef __cplusplus
extern "C" bool_t xdr_targa_t(XDR *, targa_t);
#elif __STDC__
extern  bool_t xdr_targa_t(XDR *, targa_t);
#else /* Old Style C */
bool_t xdr_targa_t();
#endif /* Old Style C */


typedef char patente_t[6];
#ifdef __cplusplus
extern "C" bool_t xdr_patente_t(XDR *, patente_t);
#elif __STDC__
extern  bool_t xdr_patente_t(XDR *, patente_t);
#else /* Old Style C */
bool_t xdr_patente_t();
#endif /* Old Style C */


typedef char tipo_t[10];
#ifdef __cplusplus
extern "C" bool_t xdr_tipo_t(XDR *, tipo_t);
#elif __STDC__
extern  bool_t xdr_tipo_t(XDR *, tipo_t);
#else /* Old Style C */
bool_t xdr_tipo_t();
#endif /* Old Style C */


typedef char img_t[12];
#ifdef __cplusplus
extern "C" bool_t xdr_img_t(XDR *, img_t);
#elif __STDC__
extern  bool_t xdr_img_t(XDR *, img_t);
#else /* Old Style C */
bool_t xdr_img_t();
#endif /* Old Style C */


struct Prenotazione {
	targa_t targa;
	patente_t patente;
	tipo_t tipo;
	img_t img;
};
typedef struct Prenotazione Prenotazione;
#ifdef __cplusplus
extern "C" bool_t xdr_Prenotazione(XDR *, Prenotazione*);
#elif __STDC__
extern  bool_t xdr_Prenotazione(XDR *, Prenotazione*);
#else /* Old Style C */
bool_t xdr_Prenotazione();
#endif /* Old Style C */


struct Input {
	targa_t targa;
	patente_t patente;
};
typedef struct Input Input;
#ifdef __cplusplus
extern "C" bool_t xdr_Input(XDR *, Input*);
#elif __STDC__
extern  bool_t xdr_Input(XDR *, Input*);
#else /* Old Style C */
bool_t xdr_Input();
#endif /* Old Style C */


struct OutputLista {
	struct Prenotazione prenotazioni[6];
	int numero_prenotazioni_trovati;
};
typedef struct OutputLista OutputLista;
#ifdef __cplusplus
extern "C" bool_t xdr_OutputLista(XDR *, OutputLista*);
#elif __STDC__
extern  bool_t xdr_OutputLista(XDR *, OutputLista*);
#else /* Old Style C */
bool_t xdr_OutputLista();
#endif /* Old Style C */


#define GESTIONE_STUDENTI_PROG ((rpc_uint)0x20000015)
#define GESTIONE_STUDENTI_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define AGGIORNA_LICENZA ((rpc_uint)1)
extern "C" int * aggiorna_licenza_1(Input *, CLIENT *);
extern "C" int * aggiorna_licenza_1_svc(Input *, struct svc_req *);
#define VISUALIZZA_PRENOTAZIONE ((rpc_uint)2)
extern "C" OutputLista * visualizza_prenotazione_1(char *, CLIENT *);
extern "C" OutputLista * visualizza_prenotazione_1_svc(char *, struct svc_req *);

#elif __STDC__
#define AGGIORNA_LICENZA ((rpc_uint)1)
extern  int * aggiorna_licenza_1(Input *, CLIENT *);
extern  int * aggiorna_licenza_1_svc(Input *, struct svc_req *);
#define VISUALIZZA_PRENOTAZIONE ((rpc_uint)2)
extern  OutputLista * visualizza_prenotazione_1(char *, CLIENT *);
extern  OutputLista * visualizza_prenotazione_1_svc(char *, struct svc_req *);

#else /* Old Style C */
#define AGGIORNA_LICENZA ((rpc_uint)1)
extern  int * aggiorna_licenza_1();
extern  int * aggiorna_licenza_1_svc();
#define VISUALIZZA_PRENOTAZIONE ((rpc_uint)2)
extern  OutputLista * visualizza_prenotazione_1();
extern  OutputLista * visualizza_prenotazione_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
