/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
aggiorna_licenza_1(argp, clnt)
	Input *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, AGGIORNA_LICENZA, xdr_Input, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

OutputLista *
visualizza_prenotazione_1(argp, clnt)
	char *argp;
	CLIENT *clnt;
{
	static OutputLista clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, VISUALIZZA_PRENOTAZIONE, xdr_targa_t, argp, xdr_OutputLista, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
