/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
elimina_prenotazione_1(argp, clnt)
	char *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ELIMINA_PRENOTAZIONE, xdr_matricola_t, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

OutputLista *
visualizza_multiple_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static OutputLista clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, VISUALIZZA_MULTIPLE, xdr_void, argp, xdr_OutputLista, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
