/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_id_t(xdrs, objp)
	XDR *xdrs;
	id_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 10, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_matricola_t(xdrs, objp)
	XDR *xdrs;
	matricola_t objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 10, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Prenotazione(xdrs, objp)
	XDR *xdrs;
	Prenotazione *objp;
{

	if (!xdr_id_t(xdrs, objp->id))
		return (FALSE);
	if (!xdr_matricola_t(xdrs, objp->matricola))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_OutputLista(xdrs, objp)
	XDR *xdrs;
	OutputLista *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->prenotazione, 5, sizeof(Prenotazione), (xdrproc_t)xdr_Prenotazione))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->numero_prenotazioni_trovati))
		return (FALSE);
	return (TRUE);
}
