/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


typedef char id_t[10];
#ifdef __cplusplus
extern "C" bool_t xdr_id_t(XDR *, id_t);
#elif __STDC__
extern  bool_t xdr_id_t(XDR *, id_t);
#else /* Old Style C */
bool_t xdr_id_t();
#endif /* Old Style C */


typedef char matricola_t[10];
#ifdef __cplusplus
extern "C" bool_t xdr_matricola_t(XDR *, matricola_t);
#elif __STDC__
extern  bool_t xdr_matricola_t(XDR *, matricola_t);
#else /* Old Style C */
bool_t xdr_matricola_t();
#endif /* Old Style C */


struct Prenotazione {
	id_t id;
	matricola_t matricola;
};
typedef struct Prenotazione Prenotazione;
#ifdef __cplusplus
extern "C" bool_t xdr_Prenotazione(XDR *, Prenotazione*);
#elif __STDC__
extern  bool_t xdr_Prenotazione(XDR *, Prenotazione*);
#else /* Old Style C */
bool_t xdr_Prenotazione();
#endif /* Old Style C */


struct OutputLista {
	struct Prenotazione prenotazione[5];
	int numero_prenotazioni_trovati;
};
typedef struct OutputLista OutputLista;
#ifdef __cplusplus
extern "C" bool_t xdr_OutputLista(XDR *, OutputLista*);
#elif __STDC__
extern  bool_t xdr_OutputLista(XDR *, OutputLista*);
#else /* Old Style C */
bool_t xdr_OutputLista();
#endif /* Old Style C */


#define GESTIONE_PRENOTAZIONI_PROG ((rpc_uint)0x20000015)
#define GESTIONE_PRENOTAZIONI_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern "C" int * elimina_prenotazione_1(char *, CLIENT *);
extern "C" int * elimina_prenotazione_1_svc(char *, struct svc_req *);
#define VISUALIZZA_MULTIPLE ((rpc_uint)2)
extern "C" OutputLista * visualizza_multiple_1(void *, CLIENT *);
extern "C" OutputLista * visualizza_multiple_1_svc(void *, struct svc_req *);

#elif __STDC__
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern  int * elimina_prenotazione_1(char *, CLIENT *);
extern  int * elimina_prenotazione_1_svc(char *, struct svc_req *);
#define VISUALIZZA_MULTIPLE ((rpc_uint)2)
extern  OutputLista * visualizza_multiple_1(void *, CLIENT *);
extern  OutputLista * visualizza_multiple_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern  int * elimina_prenotazione_1();
extern  int * elimina_prenotazione_1_svc();
#define VISUALIZZA_MULTIPLE ((rpc_uint)2)
extern  OutputLista * visualizza_multiple_1();
extern  OutputLista * visualizza_multiple_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
