/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_Candidato(XDR *xdrs, Candidato *objp)
{

	if (!xdr_string(xdrs, &objp->nome, MAX_NAME_SIZE))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->giudice, MAX_NAME_SIZE))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->categoria))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->nomeFile, MAX_FILE_SIZE))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fase, 10))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->voto))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ListaCandidati(XDR *xdrs, ListaCandidati *objp)
{

	if (!xdr_array(xdrs, (char **)&objp->ListaCandidati_val, (u_int *)&objp->ListaCandidati_len, ~0, sizeof(Candidato), (xdrproc_t)xdr_Candidato))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Giudice(XDR *xdrs, Giudice *objp)
{

	if (!xdr_string(xdrs, &objp->nomeGiudice, MAX_NAME_SIZE))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->punteggioTot))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ClassificaGiudici(XDR *xdrs, ClassificaGiudici *objp)
{

	if (!xdr_array(xdrs, (char **)&objp->ClassificaGiudici_val, (u_int *)&objp->ClassificaGiudici_len, ~0, sizeof(Giudice), (xdrproc_t)xdr_Giudice))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InputVoto(XDR *xdrs, InputVoto *objp)
{

	if (!xdr_string(xdrs, &objp->nomeCandidato, MAX_NAME_SIZE))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->tipoOp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InputSoglia(XDR *xdrs, InputSoglia *objp)
{

	if (!xdr_int(xdrs, &objp->soglia))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InputCategoria(XDR *xdrs, InputCategoria *objp)
{

	if (!xdr_char(xdrs, &objp->categoria))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InputFase(XDR *xdrs, InputFase *objp)
{

	if (!xdr_string(xdrs, &objp->nomeCandidato, MAX_NAME_SIZE))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->nuovaFase, 10))
		return (FALSE);
	return (TRUE);
}
