/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h>
#include "xfactor.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ClassificaGiudici *
classifica_giudici_1(void *argp, CLIENT *clnt)
{
	static ClassificaGiudici clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CLASSIFICA_GIUDICI, xdr_void, argp, xdr_ClassificaGiudici, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
esprimi_voto_1(InputVoto *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ESPRIMI_VOTO, xdr_InputVoto, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
aggiungi_candidato_1(Candidato *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, AGGIUNGI_CANDIDATO, xdr_Candidato, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
rimuovi_candidato_1(char **argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RIMUOVI_CANDIDATO, xdr_wrapstring, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

ListaCandidati *
lista_sopra_soglia_1(InputSoglia *argp, CLIENT *clnt)
{
	static ListaCandidati clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, LISTA_SOPRA_SOGLIA, xdr_InputSoglia, argp, xdr_ListaCandidati, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

ListaCandidati *
lista_per_categoria_1(InputCategoria *argp, CLIENT *clnt)
{
	static ListaCandidati clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, LISTA_PER_CATEGORIA, xdr_InputCategoria, argp, xdr_ListaCandidati, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
cambia_fase_1(InputFase *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CAMBIA_FASE, xdr_InputFase, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
