/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAX_NAME_SIZE 64
#define MAX_FILE_SIZE 128

struct Candidato {
	char *nome;
	char *giudice;
	char categoria;
	char *nomeFile;
	char *fase;
	int voto;
};
typedef struct Candidato Candidato;
#ifdef __cplusplus
extern "C" bool_t xdr_Candidato(XDR *, Candidato*);
#elif __STDC__
extern  bool_t xdr_Candidato(XDR *, Candidato*);
#else /* Old Style C */
bool_t xdr_Candidato();
#endif /* Old Style C */


typedef struct {
	u_int ListaCandidati_len;
	Candidato *ListaCandidati_val;
} ListaCandidati;
#ifdef __cplusplus
extern "C" bool_t xdr_ListaCandidati(XDR *, ListaCandidati*);
#elif __STDC__
extern  bool_t xdr_ListaCandidati(XDR *, ListaCandidati*);
#else /* Old Style C */
bool_t xdr_ListaCandidati();
#endif /* Old Style C */


struct Giudice {
	char *nomeGiudice;
	int punteggioTot;
};
typedef struct Giudice Giudice;
#ifdef __cplusplus
extern "C" bool_t xdr_Giudice(XDR *, Giudice*);
#elif __STDC__
extern  bool_t xdr_Giudice(XDR *, Giudice*);
#else /* Old Style C */
bool_t xdr_Giudice();
#endif /* Old Style C */


typedef struct {
	u_int ClassificaGiudici_len;
	Giudice *ClassificaGiudici_val;
} ClassificaGiudici;
#ifdef __cplusplus
extern "C" bool_t xdr_ClassificaGiudici(XDR *, ClassificaGiudici*);
#elif __STDC__
extern  bool_t xdr_ClassificaGiudici(XDR *, ClassificaGiudici*);
#else /* Old Style C */
bool_t xdr_ClassificaGiudici();
#endif /* Old Style C */


struct InputVoto {
	char *nomeCandidato;
	char tipoOp;
};
typedef struct InputVoto InputVoto;
#ifdef __cplusplus
extern "C" bool_t xdr_InputVoto(XDR *, InputVoto*);
#elif __STDC__
extern  bool_t xdr_InputVoto(XDR *, InputVoto*);
#else /* Old Style C */
bool_t xdr_InputVoto();
#endif /* Old Style C */


struct InputSoglia {
	int soglia;
};
typedef struct InputSoglia InputSoglia;
#ifdef __cplusplus
extern "C" bool_t xdr_InputSoglia(XDR *, InputSoglia*);
#elif __STDC__
extern  bool_t xdr_InputSoglia(XDR *, InputSoglia*);
#else /* Old Style C */
bool_t xdr_InputSoglia();
#endif /* Old Style C */


struct InputCategoria {
	char categoria;
};
typedef struct InputCategoria InputCategoria;
#ifdef __cplusplus
extern "C" bool_t xdr_InputCategoria(XDR *, InputCategoria*);
#elif __STDC__
extern  bool_t xdr_InputCategoria(XDR *, InputCategoria*);
#else /* Old Style C */
bool_t xdr_InputCategoria();
#endif /* Old Style C */


struct InputFase {
	char *nomeCandidato;
	char *nuovaFase;
};
typedef struct InputFase InputFase;
#ifdef __cplusplus
extern "C" bool_t xdr_InputFase(XDR *, InputFase*);
#elif __STDC__
extern  bool_t xdr_InputFase(XDR *, InputFase*);
#else /* Old Style C */
bool_t xdr_InputFase();
#endif /* Old Style C */


#define OPERATION ((rpc_uint)0x20000013)
#define OPERATIONVERS ((rpc_uint)1)

#ifdef __cplusplus
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern "C" ClassificaGiudici * classifica_giudici_1(void *, CLIENT *);
extern "C" ClassificaGiudici * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern "C" int * esprimi_voto_1(InputVoto *, CLIENT *);
extern "C" int * esprimi_voto_1_svc(InputVoto *, struct svc_req *);
#define AGGIUNGI_CANDIDATO ((rpc_uint)3)
extern "C" int * aggiungi_candidato_1(Candidato *, CLIENT *);
extern "C" int * aggiungi_candidato_1_svc(Candidato *, struct svc_req *);
#define RIMUOVI_CANDIDATO ((rpc_uint)4)
extern "C" int * rimuovi_candidato_1(char **, CLIENT *);
extern "C" int * rimuovi_candidato_1_svc(char **, struct svc_req *);
#define LISTA_SOPRA_SOGLIA ((rpc_uint)5)
extern "C" ListaCandidati * lista_sopra_soglia_1(InputSoglia *, CLIENT *);
extern "C" ListaCandidati * lista_sopra_soglia_1_svc(InputSoglia *, struct svc_req *);
#define LISTA_PER_CATEGORIA ((rpc_uint)6)
extern "C" ListaCandidati * lista_per_categoria_1(InputCategoria *, CLIENT *);
extern "C" ListaCandidati * lista_per_categoria_1_svc(InputCategoria *, struct svc_req *);
#define CAMBIA_FASE ((rpc_uint)7)
extern "C" int * cambia_fase_1(InputFase *, CLIENT *);
extern "C" int * cambia_fase_1_svc(InputFase *, struct svc_req *);

#elif __STDC__
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  ClassificaGiudici * classifica_giudici_1(void *, CLIENT *);
extern  ClassificaGiudici * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  int * esprimi_voto_1(InputVoto *, CLIENT *);
extern  int * esprimi_voto_1_svc(InputVoto *, struct svc_req *);
#define AGGIUNGI_CANDIDATO ((rpc_uint)3)
extern  int * aggiungi_candidato_1(Candidato *, CLIENT *);
extern  int * aggiungi_candidato_1_svc(Candidato *, struct svc_req *);
#define RIMUOVI_CANDIDATO ((rpc_uint)4)
extern  int * rimuovi_candidato_1(char **, CLIENT *);
extern  int * rimuovi_candidato_1_svc(char **, struct svc_req *);
#define LISTA_SOPRA_SOGLIA ((rpc_uint)5)
extern  ListaCandidati * lista_sopra_soglia_1(InputSoglia *, CLIENT *);
extern  ListaCandidati * lista_sopra_soglia_1_svc(InputSoglia *, struct svc_req *);
#define LISTA_PER_CATEGORIA ((rpc_uint)6)
extern  ListaCandidati * lista_per_categoria_1(InputCategoria *, CLIENT *);
extern  ListaCandidati * lista_per_categoria_1_svc(InputCategoria *, struct svc_req *);
#define CAMBIA_FASE ((rpc_uint)7)
extern  int * cambia_fase_1(InputFase *, CLIENT *);
extern  int * cambia_fase_1_svc(InputFase *, struct svc_req *);

#else /* Old Style C */
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  ClassificaGiudici * classifica_giudici_1();
extern  ClassificaGiudici * classifica_giudici_1_svc();
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
#define AGGIUNGI_CANDIDATO ((rpc_uint)3)
extern  int * aggiungi_candidato_1();
extern  int * aggiungi_candidato_1_svc();
#define RIMUOVI_CANDIDATO ((rpc_uint)4)
extern  int * rimuovi_candidato_1();
extern  int * rimuovi_candidato_1_svc();
#define LISTA_SOPRA_SOGLIA ((rpc_uint)5)
extern  ListaCandidati * lista_sopra_soglia_1();
extern  ListaCandidati * lista_sopra_soglia_1_svc();
#define LISTA_PER_CATEGORIA ((rpc_uint)6)
extern  ListaCandidati * lista_per_categoria_1();
extern  ListaCandidati * lista_per_categoria_1_svc();
#define CAMBIA_FASE ((rpc_uint)7)
extern  int * cambia_fase_1();
extern  int * cambia_fase_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
