/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define NUM_GIUDICI 12
#define MAX_NAME_SIZE 128

struct Giudice {
	char nomeGiudice[MAX_NAME_SIZE];
	int punteggioTot;
};
typedef struct Giudice Giudice;
#ifdef __cplusplus
extern "C" bool_t xdr_Giudice(XDR *, Giudice*);
#elif __STDC__
extern  bool_t xdr_Giudice(XDR *, Giudice*);
#else /* Old Style C */
bool_t xdr_Giudice();
#endif /* Old Style C */


struct Output {
	Giudice classificaGiudici[NUM_GIUDICI];
};
typedef struct Output Output;
#ifdef __cplusplus
extern "C" bool_t xdr_Output(XDR *, Output*);
#elif __STDC__
extern  bool_t xdr_Output(XDR *, Output*);
#else /* Old Style C */
bool_t xdr_Output();
#endif /* Old Style C */


struct Input {
	char nomeCandidato[MAX_NAME_SIZE];
	char tipoOp;
};
typedef struct Input Input;
#ifdef __cplusplus
extern "C" bool_t xdr_Input(XDR *, Input*);
#elif __STDC__
extern  bool_t xdr_Input(XDR *, Input*);
#else /* Old Style C */
bool_t xdr_Input();
#endif /* Old Style C */


struct CandidatoInfo {
	char candidato[MAX_NAME_SIZE];
	char giudice[MAX_NAME_SIZE];
	char categoria[2];
	char nomeFile[FILENAME_MAX];
	char fase[10];
	int voto;
};
typedef struct CandidatoInfo CandidatoInfo;
#ifdef __cplusplus
extern "C" bool_t xdr_CandidatoInfo(XDR *, CandidatoInfo*);
#elif __STDC__
extern  bool_t xdr_CandidatoInfo(XDR *, CandidatoInfo*);
#else /* Old Style C */
bool_t xdr_CandidatoInfo();
#endif /* Old Style C */


struct FiltroInput {
	char tipoFiltro;
	char valore[MAX_NAME_SIZE];
	int punteggioMin;
};
typedef struct FiltroInput FiltroInput;
#ifdef __cplusplus
extern "C" bool_t xdr_FiltroInput(XDR *, FiltroInput*);
#elif __STDC__
extern  bool_t xdr_FiltroInput(XDR *, FiltroInput*);
#else /* Old Style C */
bool_t xdr_FiltroInput();
#endif /* Old Style C */


#define OPERATION ((rpc_uint)0x20000013)
#define OPERATIONVERS ((rpc_uint)1)

#ifdef __cplusplus
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern "C" Output * classifica_giudici_1(void *, CLIENT *);
extern "C" Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern "C" int * esprimi_voto_1(Input *, CLIENT *);
extern "C" int * esprimi_voto_1_svc(Input *, struct svc_req *);
#define AGGIUNGI_CANDIDATO ((rpc_uint)3)
extern "C" int * aggiungi_candidato_1(CandidatoInfo *, CLIENT *);
extern "C" int * aggiungi_candidato_1_svc(CandidatoInfo *, struct svc_req *);
#define RIMUOVI_CANDIDATO ((rpc_uint)4)
extern "C" int * rimuovi_candidato_1(Input *, CLIENT *);
extern "C" int * rimuovi_candidato_1_svc(Input *, struct svc_req *);
#define CANDIDATI_FILTRATI ((rpc_uint)5)
extern "C" Output * candidati_filtrati_1(FiltroInput *, CLIENT *);
extern "C" Output * candidati_filtrati_1_svc(FiltroInput *, struct svc_req *);

#elif __STDC__
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  int * esprimi_voto_1(Input *, CLIENT *);
extern  int * esprimi_voto_1_svc(Input *, struct svc_req *);
#define AGGIUNGI_CANDIDATO ((rpc_uint)3)
extern  int * aggiungi_candidato_1(CandidatoInfo *, CLIENT *);
extern  int * aggiungi_candidato_1_svc(CandidatoInfo *, struct svc_req *);
#define RIMUOVI_CANDIDATO ((rpc_uint)4)
extern  int * rimuovi_candidato_1(Input *, CLIENT *);
extern  int * rimuovi_candidato_1_svc(Input *, struct svc_req *);
#define CANDIDATI_FILTRATI ((rpc_uint)5)
extern  Output * candidati_filtrati_1(FiltroInput *, CLIENT *);
extern  Output * candidati_filtrati_1_svc(FiltroInput *, struct svc_req *);

#else /* Old Style C */
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
#define AGGIUNGI_CANDIDATO ((rpc_uint)3)
extern  int * aggiungi_candidato_1();
extern  int * aggiungi_candidato_1_svc();
#define RIMUOVI_CANDIDATO ((rpc_uint)4)
extern  int * rimuovi_candidato_1();
extern  int * rimuovi_candidato_1_svc();
#define CANDIDATI_FILTRATI ((rpc_uint)5)
extern  Output * candidati_filtrati_1();
extern  Output * candidati_filtrati_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
