/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_Giudice(xdrs, objp)
	XDR *xdrs;
	Giudice *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->nomeGiudice, MAX_NAME_SIZE, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->punteggioTot))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Output(xdrs, objp)
	XDR *xdrs;
	Output *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->classificaGiudici, NUM_GIUDICI, sizeof(Giudice), (xdrproc_t)xdr_Giudice))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Input(xdrs, objp)
	XDR *xdrs;
	Input *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->nomeCandidato, MAX_NAME_SIZE, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->tipoOp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CandidatoInfo(xdrs, objp)
	XDR *xdrs;
	CandidatoInfo *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->candidato, MAX_NAME_SIZE, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->giudice, MAX_NAME_SIZE, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->categoria, 2, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->nomeFile, FILENAME_MAX, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->fase, 10, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->voto))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FiltroInput(xdrs, objp)
	XDR *xdrs;
	FiltroInput *objp;
{

	if (!xdr_char(xdrs, &objp->tipoFiltro))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->valore, MAX_NAME_SIZE, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->punteggioMin))
		return (FALSE);
	return (TRUE);
}
