/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Output *
classifica_giudici_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static Output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CLASSIFICA_GIUDICI, xdr_void, argp, xdr_Output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
esprimi_voto_1(argp, clnt)
	Input *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ESPRIMI_VOTO, xdr_Input, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
aggiungi_candidato_1(argp, clnt)
	CandidatoInfo *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, AGGIUNGI_CANDIDATO, xdr_CandidatoInfo, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
rimuovi_candidato_1(argp, clnt)
	Input *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RIMUOVI_CANDIDATO, xdr_Input, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

Output *
candidati_filtrati_1(argp, clnt)
	FiltroInput *argp;
	CLIENT *clnt;
{
	static Output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CANDIDATI_FILTRATI, xdr_FiltroInput, argp, xdr_Output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
